/* File generated by the BNF Converter (bnfc 2.9.4.1). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <string>
#include "Printer.H"
#define INDENT_WIDTH 2

namespace Saul
{
//You may wish to change render
void PrintAbsyn::render(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppend(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppend('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppend(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ' ') bufAppend(c);
  else if (c == 0) return;
  else
  {
     bufAppend(c);
     bufAppend(' ');
  }
}

void PrintAbsyn::render(String s)
{
  render(s.c_str());
}

bool allIsSpace(const char *s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return false;
  return true;
}

void PrintAbsyn::render(const char *s)
{
  if (*s) /* C string not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppend(s);
    } else {
      bufAppend(s);
      bufAppend(' ');
    }
  }
}

void PrintAbsyn::indent()
{
  int n = _n_;
  while (--n >= 0)
    bufAppend(' ');
}

void PrintAbsyn::backup()
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void PrintAbsyn::removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppend('\n');
  indent();
}

PrintAbsyn::PrintAbsyn(void)
{
  _i_ = 0; _n_ = 0;
  buf_ = 0;
  bufReset();
}

PrintAbsyn::~PrintAbsyn(void)
{
}

char *PrintAbsyn::print(Visitable *v)
{
  _i_ = 0; _n_ = 0;
  bufReset();
  v->accept(this);
  return buf_;
}

void PrintAbsyn::visitProgram(Program *p) {} //abstract class

void PrintAbsyn::visitAProgram(AProgram *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  _i_ = 0; p->languagedecl_->accept(this);
  _i_ = 0; visitListDecl(p->listdecl_);

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListSaulIdent(ListSaulIdent *listsaulident)
{
  iterListSaulIdent(listsaulident->begin(), listsaulident->end());
}

void PrintAbsyn::iterListSaulIdent(ListSaulIdent::const_iterator i, ListSaulIdent::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    visitSaulIdent(*i);
  }
  else
  { /* cons */
    visitSaulIdent(*i); render(','); iterListSaulIdent(i+1, j);
  }
}

void PrintAbsyn::visitLanguageDecl(LanguageDecl *p) {} //abstract class

void PrintAbsyn::visitLanguageCore(LanguageCore *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  render("language");
  render("core");
  render(';');

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDecl(Decl *p) {} //abstract class

void PrintAbsyn::visitDeclFun(DeclFun *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  _i_ = 0; visitListAnnotation(p->listannotation_);
  render("fn");
  visitSaulIdent(p->saulident_);
  render('(');
  _i_ = 0; visitListParamDecl(p->listparamdecl_);
  render(')');
  _i_ = 0; p->returntype_->accept(this);
  render('{');
  _i_ = 0; visitListDecl(p->listdecl_);
  render("return");
  _i_ = 0; p->expr_->accept(this);
  render('}');

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListDecl(ListDecl *listdecl)
{
  iterListDecl(listdecl->begin(), listdecl->end());
}

void PrintAbsyn::iterListDecl(ListDecl::const_iterator i, ListDecl::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); iterListDecl(i+1, j);
  }
}

void PrintAbsyn::visitLocalDecl(LocalDecl *p) {} //abstract class

void PrintAbsyn::visitALocalDecl(ALocalDecl *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  _i_ = 0; p->decl_->accept(this);

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListLocalDecl(ListLocalDecl *listlocaldecl)
{
  iterListLocalDecl(listlocaldecl->begin(), listlocaldecl->end());
}

void PrintAbsyn::iterListLocalDecl(ListLocalDecl::const_iterator i, ListLocalDecl::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); render(';'); iterListLocalDecl(i+1, j);
  }
}

void PrintAbsyn::visitAnnotation(Annotation *p) {} //abstract class

void PrintAbsyn::visitInlineAnnotation(InlineAnnotation *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  render("inline");

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListAnnotation(ListAnnotation *listannotation)
{
  iterListAnnotation(listannotation->begin(), listannotation->end());
}

void PrintAbsyn::iterListAnnotation(ListAnnotation::const_iterator i, ListAnnotation::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); iterListAnnotation(i+1, j);
  }
}

void PrintAbsyn::visitParamDecl(ParamDecl *p) {} //abstract class

void PrintAbsyn::visitAParamDecl(AParamDecl *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  visitSaulIdent(p->saulident_);
  render(':');
  _i_ = 0; p->type_->accept(this);

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListParamDecl(ListParamDecl *listparamdecl)
{
  iterListParamDecl(listparamdecl->begin(), listparamdecl->end());
}

void PrintAbsyn::iterListParamDecl(ListParamDecl::const_iterator i, ListParamDecl::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListParamDecl(i+1, j);
  }
}

void PrintAbsyn::visitReturnType(ReturnType *p) {} //abstract class

void PrintAbsyn::visitNoReturnType(NoReturnType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);


  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSomeReturnType(SomeReturnType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  render("->");
  _i_ = 0; p->type_->accept(this);

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitType(Type *p) {} //abstract class

void PrintAbsyn::visitTypeFun(TypeFun *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  render("fn");
  render('(');
  _i_ = 0; visitListType(p->listtype_);
  render(')');
  render("->");
  _i_ = 0; p->type_->accept(this);

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTypeSum(TypeSum *p)
{
  int oldi = _i_;
  if (oldi > 1) render(SAUL__L_PAREN);

  _i_ = 2; p->type_1->accept(this);
  render('+');
  _i_ = 2; p->type_2->accept(this);

  if (oldi > 1) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTypeTuple(TypeTuple *p)
{
  int oldi = _i_;
  if (oldi > 2) render(SAUL__L_PAREN);

  render('{');
  _i_ = 0; visitListType(p->listtype_);
  render('}');

  if (oldi > 2) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTypeRecord(TypeRecord *p)
{
  int oldi = _i_;
  if (oldi > 2) render(SAUL__L_PAREN);

  render('{');
  _i_ = 0; visitListRecordFieldType(p->listrecordfieldtype_);
  render('}');

  if (oldi > 2) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTypeBool(TypeBool *p)
{
  int oldi = _i_;
  if (oldi > 3) render(SAUL__L_PAREN);

  render("Bool");

  if (oldi > 3) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTypeNat(TypeNat *p)
{
  int oldi = _i_;
  if (oldi > 3) render(SAUL__L_PAREN);

  render("Nat");

  if (oldi > 3) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTypeUnit(TypeUnit *p)
{
  int oldi = _i_;
  if (oldi > 3) render(SAUL__L_PAREN);

  render("Unit");

  if (oldi > 3) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTypeTop(TypeTop *p)
{
  int oldi = _i_;
  if (oldi > 3) render(SAUL__L_PAREN);

  render("Top");

  if (oldi > 3) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTypeBottom(TypeBottom *p)
{
  int oldi = _i_;
  if (oldi > 3) render(SAUL__L_PAREN);

  render("Bot");

  if (oldi > 3) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTypeRef(TypeRef *p)
{
  int oldi = _i_;
  if (oldi > 3) render(SAUL__L_PAREN);

  render('&');
  _i_ = 2; p->type_->accept(this);

  if (oldi > 3) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTypeVar(TypeVar *p)
{
  int oldi = _i_;
  if (oldi > 3) render(SAUL__L_PAREN);

  visitSaulIdent(p->saulident_);

  if (oldi > 3) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListType(ListType *listtype)
{
  iterListType(listtype->begin(), listtype->end());
}

void PrintAbsyn::iterListType(ListType::const_iterator i, ListType::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    switch(_i_)
    {
      case 9: (*i)->accept(this); break;
      case 0: (*i)->accept(this); break;
    }
  }
  else
  { /* cons */
    switch(_i_)
    {
      case 9: (*i)->accept(this);
              render(',');
              iterListType(i+1, j); break;
      case 0: (*i)->accept(this);
              render(',');
              iterListType(i+1, j); break;
    }
  }
}

void PrintAbsyn::visitMatchCase(MatchCase *p) {} //abstract class

void PrintAbsyn::visitAMatchCase(AMatchCase *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  _i_ = 0; p->pattern_->accept(this);
  render("=>");
  _i_ = 0; p->expr_->accept(this);

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListMatchCase(ListMatchCase *listmatchcase)
{
  iterListMatchCase(listmatchcase->begin(), listmatchcase->end());
}

void PrintAbsyn::iterListMatchCase(ListMatchCase::const_iterator i, ListMatchCase::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render('|'); iterListMatchCase(i+1, j);
  }
}

void PrintAbsyn::visitPattern(Pattern *p) {} //abstract class

void PrintAbsyn::visitPatternInl(PatternInl *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  render("inl");
  render('(');
  _i_ = 0; p->pattern_->accept(this);
  render(')');

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPatternInr(PatternInr *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  render("inr");
  render('(');
  _i_ = 0; p->pattern_->accept(this);
  render(')');

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPatternTuple(PatternTuple *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  render('{');
  _i_ = 0; visitListPattern(p->listpattern_);
  render('}');

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPatternRecord(PatternRecord *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  render('{');
  _i_ = 0; visitListLabelledPattern(p->listlabelledpattern_);
  render('}');

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPatternFalse(PatternFalse *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  render("false");

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPatternTrue(PatternTrue *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  render("true");

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPatternUnit(PatternUnit *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  render("unit");

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPatternInt(PatternInt *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  visitInteger(p->integer_);

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPatternSucc(PatternSucc *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  render("succ");
  render('(');
  _i_ = 0; p->pattern_->accept(this);
  render(')');

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPatternVar(PatternVar *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  visitSaulIdent(p->saulident_);

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListPattern(ListPattern *listpattern)
{
  iterListPattern(listpattern->begin(), listpattern->end());
}

void PrintAbsyn::iterListPattern(ListPattern::const_iterator i, ListPattern::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListPattern(i+1, j);
  }
}

void PrintAbsyn::visitLabelledPattern(LabelledPattern *p) {} //abstract class

void PrintAbsyn::visitALabelledPattern(ALabelledPattern *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  visitSaulIdent(p->saulident_);
  render('=');
  _i_ = 0; p->pattern_->accept(this);

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListLabelledPattern(ListLabelledPattern *listlabelledpattern)
{
  iterListLabelledPattern(listlabelledpattern->begin(), listlabelledpattern->end());
}

void PrintAbsyn::iterListLabelledPattern(ListLabelledPattern::const_iterator i, ListLabelledPattern::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListLabelledPattern(i+1, j);
  }
}

void PrintAbsyn::visitBinding(Binding *p) {} //abstract class

void PrintAbsyn::visitABinding(ABinding *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  visitSaulIdent(p->saulident_);
  render('=');
  _i_ = 0; p->expr_->accept(this);

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListBinding(ListBinding *listbinding)
{
  iterListBinding(listbinding->begin(), listbinding->end());
}

void PrintAbsyn::iterListBinding(ListBinding::const_iterator i, ListBinding::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListBinding(i+1, j);
  }
}

void PrintAbsyn::visitExpr(Expr *p) {} //abstract class

void PrintAbsyn::visitSequence(Sequence *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  _i_ = 1; p->expr_1->accept(this);
  render(';');
  _i_ = 0; p->expr_2->accept(this);

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAssign(Assign *p)
{
  int oldi = _i_;
  if (oldi > 1) render(SAUL__L_PAREN);

  _i_ = 2; p->expr_1->accept(this);
  render(":=");
  _i_ = 1; p->expr_2->accept(this);

  if (oldi > 1) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIf(If *p)
{
  int oldi = _i_;
  if (oldi > 1) render(SAUL__L_PAREN);

  render("if");
  _i_ = 1; p->expr_1->accept(this);
  render("then");
  _i_ = 1; p->expr_2->accept(this);
  render("else");
  _i_ = 1; p->expr_3->accept(this);

  if (oldi > 1) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLessThan(LessThan *p)
{
  int oldi = _i_;
  if (oldi > 2) render(SAUL__L_PAREN);

  _i_ = 3; p->expr_1->accept(this);
  render('<');
  _i_ = 3; p->expr_2->accept(this);

  if (oldi > 2) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLessThanOrEqual(LessThanOrEqual *p)
{
  int oldi = _i_;
  if (oldi > 2) render(SAUL__L_PAREN);

  _i_ = 3; p->expr_1->accept(this);
  render("<=");
  _i_ = 3; p->expr_2->accept(this);

  if (oldi > 2) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitGreaterThan(GreaterThan *p)
{
  int oldi = _i_;
  if (oldi > 2) render(SAUL__L_PAREN);

  _i_ = 3; p->expr_1->accept(this);
  render('>');
  _i_ = 3; p->expr_2->accept(this);

  if (oldi > 2) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitGreaterThanOrEqual(GreaterThanOrEqual *p)
{
  int oldi = _i_;
  if (oldi > 2) render(SAUL__L_PAREN);

  _i_ = 3; p->expr_1->accept(this);
  render(">=");
  _i_ = 3; p->expr_2->accept(this);

  if (oldi > 2) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEqual(Equal *p)
{
  int oldi = _i_;
  if (oldi > 2) render(SAUL__L_PAREN);

  _i_ = 3; p->expr_1->accept(this);
  render("==");
  _i_ = 3; p->expr_2->accept(this);

  if (oldi > 2) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitNotEqual(NotEqual *p)
{
  int oldi = _i_;
  if (oldi > 2) render(SAUL__L_PAREN);

  _i_ = 3; p->expr_1->accept(this);
  render("!=");
  _i_ = 3; p->expr_2->accept(this);

  if (oldi > 2) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAbstraction(Abstraction *p)
{
  int oldi = _i_;
  if (oldi > 3) render(SAUL__L_PAREN);

  render("fn");
  render('(');
  _i_ = 0; visitListParamDecl(p->listparamdecl_);
  render(')');
  render('{');
  render("return");
  _i_ = 0; p->expr_->accept(this);
  render('}');

  if (oldi > 3) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitMatch(Match *p)
{
  int oldi = _i_;
  if (oldi > 3) render(SAUL__L_PAREN);

  render("match");
  _i_ = 2; p->expr_->accept(this);
  render('{');
  _i_ = 0; visitListMatchCase(p->listmatchcase_);
  render('}');

  if (oldi > 3) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAdd(Add *p)
{
  int oldi = _i_;
  if (oldi > 3) render(SAUL__L_PAREN);

  _i_ = 3; p->expr_1->accept(this);
  render('+');
  _i_ = 4; p->expr_2->accept(this);

  if (oldi > 3) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSubtract(Subtract *p)
{
  int oldi = _i_;
  if (oldi > 3) render(SAUL__L_PAREN);

  _i_ = 3; p->expr_1->accept(this);
  render('-');
  _i_ = 4; p->expr_2->accept(this);

  if (oldi > 3) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLogicOr(LogicOr *p)
{
  int oldi = _i_;
  if (oldi > 3) render(SAUL__L_PAREN);

  _i_ = 3; p->expr_1->accept(this);
  render("or");
  _i_ = 4; p->expr_2->accept(this);

  if (oldi > 3) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitMultiply(Multiply *p)
{
  int oldi = _i_;
  if (oldi > 4) render(SAUL__L_PAREN);

  _i_ = 4; p->expr_1->accept(this);
  render('*');
  _i_ = 5; p->expr_2->accept(this);

  if (oldi > 4) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDivide(Divide *p)
{
  int oldi = _i_;
  if (oldi > 4) render(SAUL__L_PAREN);

  _i_ = 4; p->expr_1->accept(this);
  render('/');
  _i_ = 5; p->expr_2->accept(this);

  if (oldi > 4) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLogicAnd(LogicAnd *p)
{
  int oldi = _i_;
  if (oldi > 4) render(SAUL__L_PAREN);

  _i_ = 4; p->expr_1->accept(this);
  render("and");
  _i_ = 5; p->expr_2->accept(this);

  if (oldi > 4) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRef(Ref *p)
{
  int oldi = _i_;
  if (oldi > 5) render(SAUL__L_PAREN);

  render("new");
  render('(');
  _i_ = 5; p->expr_->accept(this);
  render(')');

  if (oldi > 5) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDeref(Deref *p)
{
  int oldi = _i_;
  if (oldi > 5) render(SAUL__L_PAREN);

  render('*');
  _i_ = 5; p->expr_->accept(this);

  if (oldi > 5) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitApplication(Application *p)
{
  int oldi = _i_;
  if (oldi > 6) render(SAUL__L_PAREN);

  _i_ = 6; p->expr_->accept(this);
  render('(');
  _i_ = 0; visitListExpr(p->listexpr_);
  render(')');

  if (oldi > 6) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDotRecord(DotRecord *p)
{
  int oldi = _i_;
  if (oldi > 6) render(SAUL__L_PAREN);

  _i_ = 6; p->expr_->accept(this);
  render('.');
  visitSaulIdent(p->saulident_);

  if (oldi > 6) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDotTuple(DotTuple *p)
{
  int oldi = _i_;
  if (oldi > 6) render(SAUL__L_PAREN);

  _i_ = 6; p->expr_->accept(this);
  render('.');
  visitInteger(p->integer_);

  if (oldi > 6) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTuple(Tuple *p)
{
  int oldi = _i_;
  if (oldi > 6) render(SAUL__L_PAREN);

  render('{');
  _i_ = 0; visitListExpr(p->listexpr_);
  render('}');

  if (oldi > 6) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRecord(Record *p)
{
  int oldi = _i_;
  if (oldi > 6) render(SAUL__L_PAREN);

  render('{');
  _i_ = 0; visitListBinding(p->listbinding_);
  render('}');

  if (oldi > 6) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPanic(Panic *p)
{
  int oldi = _i_;
  if (oldi > 6) render(SAUL__L_PAREN);

  render("panic!");

  if (oldi > 6) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitInl(Inl *p)
{
  int oldi = _i_;
  if (oldi > 6) render(SAUL__L_PAREN);

  render("inl");
  render('(');
  _i_ = 0; p->expr_->accept(this);
  render(')');

  if (oldi > 6) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitInr(Inr *p)
{
  int oldi = _i_;
  if (oldi > 6) render(SAUL__L_PAREN);

  render("inr");
  render('(');
  _i_ = 0; p->expr_->accept(this);
  render(')');

  if (oldi > 6) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSucc(Succ *p)
{
  int oldi = _i_;
  if (oldi > 6) render(SAUL__L_PAREN);

  render("succ");
  render('(');
  _i_ = 0; p->expr_->accept(this);
  render(')');

  if (oldi > 6) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLogicNot(LogicNot *p)
{
  int oldi = _i_;
  if (oldi > 6) render(SAUL__L_PAREN);

  render("not");
  render('(');
  _i_ = 0; p->expr_->accept(this);
  render(')');

  if (oldi > 6) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPred(Pred *p)
{
  int oldi = _i_;
  if (oldi > 6) render(SAUL__L_PAREN);

  render("Nat::pred");
  render('(');
  _i_ = 0; p->expr_->accept(this);
  render(')');

  if (oldi > 6) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIsZero(IsZero *p)
{
  int oldi = _i_;
  if (oldi > 6) render(SAUL__L_PAREN);

  render("Nat::iszero");
  render('(');
  _i_ = 0; p->expr_->accept(this);
  render(')');

  if (oldi > 6) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitNatRec(NatRec *p)
{
  int oldi = _i_;
  if (oldi > 6) render(SAUL__L_PAREN);

  render("Nat::rec");
  render('(');
  _i_ = 0; p->expr_1->accept(this);
  render(',');
  _i_ = 0; p->expr_2->accept(this);
  render(',');
  _i_ = 0; p->expr_3->accept(this);
  render(')');

  if (oldi > 6) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitConstTrue(ConstTrue *p)
{
  int oldi = _i_;
  if (oldi > 7) render(SAUL__L_PAREN);

  render("true");

  if (oldi > 7) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitConstFalse(ConstFalse *p)
{
  int oldi = _i_;
  if (oldi > 7) render(SAUL__L_PAREN);

  render("false");

  if (oldi > 7) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitConstUnit(ConstUnit *p)
{
  int oldi = _i_;
  if (oldi > 7) render(SAUL__L_PAREN);

  render("unit");

  if (oldi > 7) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitConstInt(ConstInt *p)
{
  int oldi = _i_;
  if (oldi > 7) render(SAUL__L_PAREN);

  visitInteger(p->integer_);

  if (oldi > 7) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVar(Var *p)
{
  int oldi = _i_;
  if (oldi > 7) render(SAUL__L_PAREN);

  visitSaulIdent(p->saulident_);

  if (oldi > 7) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListExpr(ListExpr *listexpr)
{
  iterListExpr(listexpr->begin(), listexpr->end());
}

void PrintAbsyn::iterListExpr(ListExpr::const_iterator i, ListExpr::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    switch(_i_)
    {
      case 2: (*i)->accept(this); render(';'); break;
      case 0: (*i)->accept(this); break;
    }
  }
  else
  { /* cons */
    switch(_i_)
    {
      case 2: (*i)->accept(this);
              render(';');
              iterListExpr(i+1, j); break;
      case 0: (*i)->accept(this);
              render(',');
              iterListExpr(i+1, j); break;
    }
  }
}

void PrintAbsyn::visitRecordFieldType(RecordFieldType *p) {} //abstract class

void PrintAbsyn::visitARecordFieldType(ARecordFieldType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(SAUL__L_PAREN);

  visitSaulIdent(p->saulident_);
  render(':');
  _i_ = 0; p->type_->accept(this);

  if (oldi > 0) render(SAUL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListRecordFieldType(ListRecordFieldType *listrecordfieldtype)
{
  iterListRecordFieldType(listrecordfieldtype->begin(), listrecordfieldtype->end());
}

void PrintAbsyn::iterListRecordFieldType(ListRecordFieldType::const_iterator i, ListRecordFieldType::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListRecordFieldType(i+1, j);
  }
}

void PrintAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  render(tmp);
}

void PrintAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  render(tmp);
}

void PrintAbsyn::visitChar(Char c)
{
  char tmp[4];
  sprintf(tmp, "'%c'", c);
  render(tmp);
}

void PrintAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
  bufAppend(' ');
}

void PrintAbsyn::visitIdent(String s)
{
  render(s);
}

void PrintAbsyn::visitSaulIdent(String s)
{
  render(s);
}


ShowAbsyn::ShowAbsyn(void)
{
  buf_ = 0;
  bufReset();
}

ShowAbsyn::~ShowAbsyn(void)
{
}

char *ShowAbsyn::show(Visitable *v)
{
  bufReset();
  v->accept(this);
  return buf_;
}

void ShowAbsyn::visitProgram(Program *p) {} //abstract class

void ShowAbsyn::visitAProgram(AProgram *p)
{
  bufAppend('(');
  bufAppend("AProgram");
  bufAppend(' ');
  bufAppend('[');
  if (p->languagedecl_)  p->languagedecl_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listdecl_)  p->listdecl_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListSaulIdent(ListSaulIdent *listsaulident)
{
  for (ListSaulIdent::const_iterator i = listsaulident->begin() ; i != listsaulident->end() ; ++i)
  {
    visitSaulIdent(*i) ;
    if (i != listsaulident->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitLanguageDecl(LanguageDecl *p) {} //abstract class

void ShowAbsyn::visitLanguageCore(LanguageCore *p)
{
  bufAppend("LanguageCore");
}
void ShowAbsyn::visitDecl(Decl *p) {} //abstract class

void ShowAbsyn::visitDeclFun(DeclFun *p)
{
  bufAppend('(');
  bufAppend("DeclFun");
  bufAppend(' ');
  bufAppend('[');
  if (p->listannotation_)  p->listannotation_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitSaulIdent(p->saulident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->listparamdecl_)  p->listparamdecl_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->returntype_)  p->returntype_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listdecl_)  p->listdecl_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListDecl(ListDecl *listdecl)
{
  for (ListDecl::const_iterator i = listdecl->begin() ; i != listdecl->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listdecl->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitLocalDecl(LocalDecl *p) {} //abstract class

void ShowAbsyn::visitALocalDecl(ALocalDecl *p)
{
  bufAppend('(');
  bufAppend("ALocalDecl");
  bufAppend(' ');
  bufAppend('[');
  if (p->decl_)  p->decl_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListLocalDecl(ListLocalDecl *listlocaldecl)
{
  for (ListLocalDecl::const_iterator i = listlocaldecl->begin() ; i != listlocaldecl->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listlocaldecl->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitAnnotation(Annotation *p) {} //abstract class

void ShowAbsyn::visitInlineAnnotation(InlineAnnotation *p)
{
  bufAppend("InlineAnnotation");
}
void ShowAbsyn::visitListAnnotation(ListAnnotation *listannotation)
{
  for (ListAnnotation::const_iterator i = listannotation->begin() ; i != listannotation->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listannotation->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitParamDecl(ParamDecl *p) {} //abstract class

void ShowAbsyn::visitAParamDecl(AParamDecl *p)
{
  bufAppend('(');
  bufAppend("AParamDecl");
  bufAppend(' ');
  visitSaulIdent(p->saulident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListParamDecl(ListParamDecl *listparamdecl)
{
  for (ListParamDecl::const_iterator i = listparamdecl->begin() ; i != listparamdecl->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listparamdecl->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitReturnType(ReturnType *p) {} //abstract class

void ShowAbsyn::visitNoReturnType(NoReturnType *p)
{
  bufAppend("NoReturnType");
}
void ShowAbsyn::visitSomeReturnType(SomeReturnType *p)
{
  bufAppend('(');
  bufAppend("SomeReturnType");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitType(Type *p) {} //abstract class

void ShowAbsyn::visitTypeFun(TypeFun *p)
{
  bufAppend('(');
  bufAppend("TypeFun");
  bufAppend(' ');
  bufAppend('[');
  if (p->listtype_)  p->listtype_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitTypeSum(TypeSum *p)
{
  bufAppend('(');
  bufAppend("TypeSum");
  bufAppend(' ');
  p->type_1->accept(this);
  bufAppend(' ');
  p->type_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitTypeTuple(TypeTuple *p)
{
  bufAppend('(');
  bufAppend("TypeTuple");
  bufAppend(' ');
  bufAppend('[');
  if (p->listtype_)  p->listtype_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitTypeRecord(TypeRecord *p)
{
  bufAppend('(');
  bufAppend("TypeRecord");
  bufAppend(' ');
  bufAppend('[');
  if (p->listrecordfieldtype_)  p->listrecordfieldtype_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitTypeBool(TypeBool *p)
{
  bufAppend("TypeBool");
}
void ShowAbsyn::visitTypeNat(TypeNat *p)
{
  bufAppend("TypeNat");
}
void ShowAbsyn::visitTypeUnit(TypeUnit *p)
{
  bufAppend("TypeUnit");
}
void ShowAbsyn::visitTypeTop(TypeTop *p)
{
  bufAppend("TypeTop");
}
void ShowAbsyn::visitTypeBottom(TypeBottom *p)
{
  bufAppend("TypeBottom");
}
void ShowAbsyn::visitTypeRef(TypeRef *p)
{
  bufAppend('(');
  bufAppend("TypeRef");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitTypeVar(TypeVar *p)
{
  bufAppend('(');
  bufAppend("TypeVar");
  bufAppend(' ');
  visitSaulIdent(p->saulident_);
  bufAppend(')');
}
void ShowAbsyn::visitListType(ListType *listtype)
{
  for (ListType::const_iterator i = listtype->begin() ; i != listtype->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listtype->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitMatchCase(MatchCase *p) {} //abstract class

void ShowAbsyn::visitAMatchCase(AMatchCase *p)
{
  bufAppend('(');
  bufAppend("AMatchCase");
  bufAppend(' ');
  bufAppend('[');
  if (p->pattern_)  p->pattern_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListMatchCase(ListMatchCase *listmatchcase)
{
  for (ListMatchCase::const_iterator i = listmatchcase->begin() ; i != listmatchcase->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listmatchcase->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitPattern(Pattern *p) {} //abstract class

void ShowAbsyn::visitPatternInl(PatternInl *p)
{
  bufAppend('(');
  bufAppend("PatternInl");
  bufAppend(' ');
  bufAppend('[');
  if (p->pattern_)  p->pattern_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitPatternInr(PatternInr *p)
{
  bufAppend('(');
  bufAppend("PatternInr");
  bufAppend(' ');
  bufAppend('[');
  if (p->pattern_)  p->pattern_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitPatternTuple(PatternTuple *p)
{
  bufAppend('(');
  bufAppend("PatternTuple");
  bufAppend(' ');
  bufAppend('[');
  if (p->listpattern_)  p->listpattern_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitPatternRecord(PatternRecord *p)
{
  bufAppend('(');
  bufAppend("PatternRecord");
  bufAppend(' ');
  bufAppend('[');
  if (p->listlabelledpattern_)  p->listlabelledpattern_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitPatternFalse(PatternFalse *p)
{
  bufAppend("PatternFalse");
}
void ShowAbsyn::visitPatternTrue(PatternTrue *p)
{
  bufAppend("PatternTrue");
}
void ShowAbsyn::visitPatternUnit(PatternUnit *p)
{
  bufAppend("PatternUnit");
}
void ShowAbsyn::visitPatternInt(PatternInt *p)
{
  bufAppend('(');
  bufAppend("PatternInt");
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitPatternSucc(PatternSucc *p)
{
  bufAppend('(');
  bufAppend("PatternSucc");
  bufAppend(' ');
  bufAppend('[');
  if (p->pattern_)  p->pattern_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitPatternVar(PatternVar *p)
{
  bufAppend('(');
  bufAppend("PatternVar");
  bufAppend(' ');
  visitSaulIdent(p->saulident_);
  bufAppend(')');
}
void ShowAbsyn::visitListPattern(ListPattern *listpattern)
{
  for (ListPattern::const_iterator i = listpattern->begin() ; i != listpattern->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listpattern->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitLabelledPattern(LabelledPattern *p) {} //abstract class

void ShowAbsyn::visitALabelledPattern(ALabelledPattern *p)
{
  bufAppend('(');
  bufAppend("ALabelledPattern");
  bufAppend(' ');
  visitSaulIdent(p->saulident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->pattern_)  p->pattern_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListLabelledPattern(ListLabelledPattern *listlabelledpattern)
{
  for (ListLabelledPattern::const_iterator i = listlabelledpattern->begin() ; i != listlabelledpattern->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listlabelledpattern->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitBinding(Binding *p) {} //abstract class

void ShowAbsyn::visitABinding(ABinding *p)
{
  bufAppend('(');
  bufAppend("ABinding");
  bufAppend(' ');
  visitSaulIdent(p->saulident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListBinding(ListBinding *listbinding)
{
  for (ListBinding::const_iterator i = listbinding->begin() ; i != listbinding->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listbinding->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitExpr(Expr *p) {} //abstract class

void ShowAbsyn::visitSequence(Sequence *p)
{
  bufAppend('(');
  bufAppend("Sequence");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitAssign(Assign *p)
{
  bufAppend('(');
  bufAppend("Assign");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitIf(If *p)
{
  bufAppend('(');
  bufAppend("If");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(' ');
  p->expr_3->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLessThan(LessThan *p)
{
  bufAppend('(');
  bufAppend("LessThan");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLessThanOrEqual(LessThanOrEqual *p)
{
  bufAppend('(');
  bufAppend("LessThanOrEqual");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitGreaterThan(GreaterThan *p)
{
  bufAppend('(');
  bufAppend("GreaterThan");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitGreaterThanOrEqual(GreaterThanOrEqual *p)
{
  bufAppend('(');
  bufAppend("GreaterThanOrEqual");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitEqual(Equal *p)
{
  bufAppend('(');
  bufAppend("Equal");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitNotEqual(NotEqual *p)
{
  bufAppend('(');
  bufAppend("NotEqual");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitAbstraction(Abstraction *p)
{
  bufAppend('(');
  bufAppend("Abstraction");
  bufAppend(' ');
  bufAppend('[');
  if (p->listparamdecl_)  p->listparamdecl_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitMatch(Match *p)
{
  bufAppend('(');
  bufAppend("Match");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listmatchcase_)  p->listmatchcase_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitAdd(Add *p)
{
  bufAppend('(');
  bufAppend("Add");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitSubtract(Subtract *p)
{
  bufAppend('(');
  bufAppend("Subtract");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLogicOr(LogicOr *p)
{
  bufAppend('(');
  bufAppend("LogicOr");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitMultiply(Multiply *p)
{
  bufAppend('(');
  bufAppend("Multiply");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitDivide(Divide *p)
{
  bufAppend('(');
  bufAppend("Divide");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLogicAnd(LogicAnd *p)
{
  bufAppend('(');
  bufAppend("LogicAnd");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitRef(Ref *p)
{
  bufAppend('(');
  bufAppend("Ref");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitDeref(Deref *p)
{
  bufAppend('(');
  bufAppend("Deref");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitApplication(Application *p)
{
  bufAppend('(');
  bufAppend("Application");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listexpr_)  p->listexpr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitDotRecord(DotRecord *p)
{
  bufAppend('(');
  bufAppend("DotRecord");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitSaulIdent(p->saulident_);
  bufAppend(')');
}
void ShowAbsyn::visitDotTuple(DotTuple *p)
{
  bufAppend('(');
  bufAppend("DotTuple");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitTuple(Tuple *p)
{
  bufAppend('(');
  bufAppend("Tuple");
  bufAppend(' ');
  bufAppend('[');
  if (p->listexpr_)  p->listexpr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRecord(Record *p)
{
  bufAppend('(');
  bufAppend("Record");
  bufAppend(' ');
  bufAppend('[');
  if (p->listbinding_)  p->listbinding_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitPanic(Panic *p)
{
  bufAppend("Panic");
}
void ShowAbsyn::visitInl(Inl *p)
{
  bufAppend('(');
  bufAppend("Inl");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitInr(Inr *p)
{
  bufAppend('(');
  bufAppend("Inr");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitSucc(Succ *p)
{
  bufAppend('(');
  bufAppend("Succ");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitLogicNot(LogicNot *p)
{
  bufAppend('(');
  bufAppend("LogicNot");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitPred(Pred *p)
{
  bufAppend('(');
  bufAppend("Pred");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitIsZero(IsZero *p)
{
  bufAppend('(');
  bufAppend("IsZero");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitNatRec(NatRec *p)
{
  bufAppend('(');
  bufAppend("NatRec");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(' ');
  p->expr_3->accept(this);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitConstTrue(ConstTrue *p)
{
  bufAppend("ConstTrue");
}
void ShowAbsyn::visitConstFalse(ConstFalse *p)
{
  bufAppend("ConstFalse");
}
void ShowAbsyn::visitConstUnit(ConstUnit *p)
{
  bufAppend("ConstUnit");
}
void ShowAbsyn::visitConstInt(ConstInt *p)
{
  bufAppend('(');
  bufAppend("ConstInt");
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitVar(Var *p)
{
  bufAppend('(');
  bufAppend("Var");
  bufAppend(' ');
  visitSaulIdent(p->saulident_);
  bufAppend(')');
}
void ShowAbsyn::visitListExpr(ListExpr *listexpr)
{
  for (ListExpr::const_iterator i = listexpr->begin() ; i != listexpr->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listexpr->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitRecordFieldType(RecordFieldType *p) {} //abstract class

void ShowAbsyn::visitARecordFieldType(ARecordFieldType *p)
{
  bufAppend('(');
  bufAppend("ARecordFieldType");
  bufAppend(' ');
  visitSaulIdent(p->saulident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListRecordFieldType(ListRecordFieldType *listrecordfieldtype)
{
  for (ListRecordFieldType::const_iterator i = listrecordfieldtype->begin() ; i != listrecordfieldtype->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listrecordfieldtype->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppend(tmp);
}
void ShowAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppend(tmp);
}
void ShowAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufAppend(c);
  bufAppend('\'');
}
void ShowAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}
void ShowAbsyn::visitIdent(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}

void ShowAbsyn::visitSaulIdent(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}


}
