/* File generated by the BNF Converter (bnfc 2.9.4.1). */

/*** Visitor Design Pattern Skeleton. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "Skeleton.H"


namespace Saul
{
void Skeleton::visitProgram(Program *t) {} //abstract class
void Skeleton::visitLanguageDecl(LanguageDecl *t) {} //abstract class
void Skeleton::visitDecl(Decl *t) {} //abstract class
void Skeleton::visitLocalDecl(LocalDecl *t) {} //abstract class
void Skeleton::visitAnnotation(Annotation *t) {} //abstract class
void Skeleton::visitParamDecl(ParamDecl *t) {} //abstract class
void Skeleton::visitReturnType(ReturnType *t) {} //abstract class
void Skeleton::visitType(Type *t) {} //abstract class
void Skeleton::visitMatchCase(MatchCase *t) {} //abstract class
void Skeleton::visitPattern(Pattern *t) {} //abstract class
void Skeleton::visitLabelledPattern(LabelledPattern *t) {} //abstract class
void Skeleton::visitBinding(Binding *t) {} //abstract class
void Skeleton::visitExpr(Expr *t) {} //abstract class
void Skeleton::visitRecordFieldType(RecordFieldType *t) {} //abstract class

void Skeleton::visitAProgram(AProgram *a_program)
{
  /* Code For AProgram Goes Here */

  if (a_program->languagedecl_) a_program->languagedecl_->accept(this);
  if (a_program->listdecl_) a_program->listdecl_->accept(this);

}

void Skeleton::visitLanguageCore(LanguageCore *language_core)
{
  /* Code For LanguageCore Goes Here */


}

void Skeleton::visitDeclFun(DeclFun *decl_fun)
{
  /* Code For DeclFun Goes Here */

  if (decl_fun->listannotation_) decl_fun->listannotation_->accept(this);
  visitSaulIdent(decl_fun->saulident_);
  if (decl_fun->listparamdecl_) decl_fun->listparamdecl_->accept(this);
  if (decl_fun->returntype_) decl_fun->returntype_->accept(this);
  if (decl_fun->listdecl_) decl_fun->listdecl_->accept(this);
  if (decl_fun->expr_) decl_fun->expr_->accept(this);

}

void Skeleton::visitALocalDecl(ALocalDecl *a_local_decl)
{
  /* Code For ALocalDecl Goes Here */

  if (a_local_decl->decl_) a_local_decl->decl_->accept(this);

}

void Skeleton::visitInlineAnnotation(InlineAnnotation *inline_annotation)
{
  /* Code For InlineAnnotation Goes Here */


}

void Skeleton::visitAParamDecl(AParamDecl *a_param_decl)
{
  /* Code For AParamDecl Goes Here */

  visitSaulIdent(a_param_decl->saulident_);
  if (a_param_decl->type_) a_param_decl->type_->accept(this);

}

void Skeleton::visitNoReturnType(NoReturnType *no_return_type)
{
  /* Code For NoReturnType Goes Here */


}

void Skeleton::visitSomeReturnType(SomeReturnType *some_return_type)
{
  /* Code For SomeReturnType Goes Here */

  if (some_return_type->type_) some_return_type->type_->accept(this);

}

void Skeleton::visitTypeFun(TypeFun *type_fun)
{
  /* Code For TypeFun Goes Here */

  if (type_fun->listtype_) type_fun->listtype_->accept(this);
  if (type_fun->type_) type_fun->type_->accept(this);

}

void Skeleton::visitTypeSum(TypeSum *type_sum)
{
  /* Code For TypeSum Goes Here */

  if (type_sum->type_1) type_sum->type_1->accept(this);
  if (type_sum->type_2) type_sum->type_2->accept(this);

}

void Skeleton::visitTypeTuple(TypeTuple *type_tuple)
{
  /* Code For TypeTuple Goes Here */

  if (type_tuple->listtype_) type_tuple->listtype_->accept(this);

}

void Skeleton::visitTypeRecord(TypeRecord *type_record)
{
  /* Code For TypeRecord Goes Here */

  if (type_record->listrecordfieldtype_) type_record->listrecordfieldtype_->accept(this);

}

void Skeleton::visitTypeBool(TypeBool *type_bool)
{
  /* Code For TypeBool Goes Here */


}

void Skeleton::visitTypeNat(TypeNat *type_nat)
{
  /* Code For TypeNat Goes Here */


}

void Skeleton::visitTypeUnit(TypeUnit *type_unit)
{
  /* Code For TypeUnit Goes Here */


}

void Skeleton::visitTypeTop(TypeTop *type_top)
{
  /* Code For TypeTop Goes Here */


}

void Skeleton::visitTypeBottom(TypeBottom *type_bottom)
{
  /* Code For TypeBottom Goes Here */


}

void Skeleton::visitTypeRef(TypeRef *type_ref)
{
  /* Code For TypeRef Goes Here */

  if (type_ref->type_) type_ref->type_->accept(this);

}

void Skeleton::visitTypeVar(TypeVar *type_var)
{
  /* Code For TypeVar Goes Here */

  visitSaulIdent(type_var->saulident_);

}

void Skeleton::visitAMatchCase(AMatchCase *a_match_case)
{
  /* Code For AMatchCase Goes Here */

  if (a_match_case->pattern_) a_match_case->pattern_->accept(this);
  if (a_match_case->expr_) a_match_case->expr_->accept(this);

}

void Skeleton::visitPatternInl(PatternInl *pattern_inl)
{
  /* Code For PatternInl Goes Here */

  if (pattern_inl->pattern_) pattern_inl->pattern_->accept(this);

}

void Skeleton::visitPatternInr(PatternInr *pattern_inr)
{
  /* Code For PatternInr Goes Here */

  if (pattern_inr->pattern_) pattern_inr->pattern_->accept(this);

}

void Skeleton::visitPatternTuple(PatternTuple *pattern_tuple)
{
  /* Code For PatternTuple Goes Here */

  if (pattern_tuple->listpattern_) pattern_tuple->listpattern_->accept(this);

}

void Skeleton::visitPatternRecord(PatternRecord *pattern_record)
{
  /* Code For PatternRecord Goes Here */

  if (pattern_record->listlabelledpattern_) pattern_record->listlabelledpattern_->accept(this);

}

void Skeleton::visitPatternFalse(PatternFalse *pattern_false)
{
  /* Code For PatternFalse Goes Here */


}

void Skeleton::visitPatternTrue(PatternTrue *pattern_true)
{
  /* Code For PatternTrue Goes Here */


}

void Skeleton::visitPatternUnit(PatternUnit *pattern_unit)
{
  /* Code For PatternUnit Goes Here */


}

void Skeleton::visitPatternInt(PatternInt *pattern_int)
{
  /* Code For PatternInt Goes Here */

  visitInteger(pattern_int->integer_);

}

void Skeleton::visitPatternSucc(PatternSucc *pattern_succ)
{
  /* Code For PatternSucc Goes Here */

  if (pattern_succ->pattern_) pattern_succ->pattern_->accept(this);

}

void Skeleton::visitPatternVar(PatternVar *pattern_var)
{
  /* Code For PatternVar Goes Here */

  visitSaulIdent(pattern_var->saulident_);

}

void Skeleton::visitALabelledPattern(ALabelledPattern *a_labelled_pattern)
{
  /* Code For ALabelledPattern Goes Here */

  visitSaulIdent(a_labelled_pattern->saulident_);
  if (a_labelled_pattern->pattern_) a_labelled_pattern->pattern_->accept(this);

}

void Skeleton::visitABinding(ABinding *a_binding)
{
  /* Code For ABinding Goes Here */

  visitSaulIdent(a_binding->saulident_);
  if (a_binding->expr_) a_binding->expr_->accept(this);

}

void Skeleton::visitSequence(Sequence *sequence)
{
  /* Code For Sequence Goes Here */

  if (sequence->expr_1) sequence->expr_1->accept(this);
  if (sequence->expr_2) sequence->expr_2->accept(this);

}

void Skeleton::visitAssign(Assign *assign)
{
  /* Code For Assign Goes Here */

  if (assign->expr_1) assign->expr_1->accept(this);
  if (assign->expr_2) assign->expr_2->accept(this);

}

void Skeleton::visitIf(If *if_)
{
  /* Code For If Goes Here */

  if (if_->expr_1) if_->expr_1->accept(this);
  if (if_->expr_2) if_->expr_2->accept(this);
  if (if_->expr_3) if_->expr_3->accept(this);

}

void Skeleton::visitLessThan(LessThan *less_than)
{
  /* Code For LessThan Goes Here */

  if (less_than->expr_1) less_than->expr_1->accept(this);
  if (less_than->expr_2) less_than->expr_2->accept(this);

}

void Skeleton::visitLessThanOrEqual(LessThanOrEqual *less_than_or_equal)
{
  /* Code For LessThanOrEqual Goes Here */

  if (less_than_or_equal->expr_1) less_than_or_equal->expr_1->accept(this);
  if (less_than_or_equal->expr_2) less_than_or_equal->expr_2->accept(this);

}

void Skeleton::visitGreaterThan(GreaterThan *greater_than)
{
  /* Code For GreaterThan Goes Here */

  if (greater_than->expr_1) greater_than->expr_1->accept(this);
  if (greater_than->expr_2) greater_than->expr_2->accept(this);

}

void Skeleton::visitGreaterThanOrEqual(GreaterThanOrEqual *greater_than_or_equal)
{
  /* Code For GreaterThanOrEqual Goes Here */

  if (greater_than_or_equal->expr_1) greater_than_or_equal->expr_1->accept(this);
  if (greater_than_or_equal->expr_2) greater_than_or_equal->expr_2->accept(this);

}

void Skeleton::visitEqual(Equal *equal)
{
  /* Code For Equal Goes Here */

  if (equal->expr_1) equal->expr_1->accept(this);
  if (equal->expr_2) equal->expr_2->accept(this);

}

void Skeleton::visitNotEqual(NotEqual *not_equal)
{
  /* Code For NotEqual Goes Here */

  if (not_equal->expr_1) not_equal->expr_1->accept(this);
  if (not_equal->expr_2) not_equal->expr_2->accept(this);

}

void Skeleton::visitAbstraction(Abstraction *abstraction)
{
  /* Code For Abstraction Goes Here */

  if (abstraction->listparamdecl_) abstraction->listparamdecl_->accept(this);
  if (abstraction->expr_) abstraction->expr_->accept(this);

}

void Skeleton::visitMatch(Match *match)
{
  /* Code For Match Goes Here */

  if (match->expr_) match->expr_->accept(this);
  if (match->listmatchcase_) match->listmatchcase_->accept(this);

}

void Skeleton::visitAdd(Add *add)
{
  /* Code For Add Goes Here */

  if (add->expr_1) add->expr_1->accept(this);
  if (add->expr_2) add->expr_2->accept(this);

}

void Skeleton::visitSubtract(Subtract *subtract)
{
  /* Code For Subtract Goes Here */

  if (subtract->expr_1) subtract->expr_1->accept(this);
  if (subtract->expr_2) subtract->expr_2->accept(this);

}

void Skeleton::visitLogicOr(LogicOr *logic_or)
{
  /* Code For LogicOr Goes Here */

  if (logic_or->expr_1) logic_or->expr_1->accept(this);
  if (logic_or->expr_2) logic_or->expr_2->accept(this);

}

void Skeleton::visitMultiply(Multiply *multiply)
{
  /* Code For Multiply Goes Here */

  if (multiply->expr_1) multiply->expr_1->accept(this);
  if (multiply->expr_2) multiply->expr_2->accept(this);

}

void Skeleton::visitDivide(Divide *divide)
{
  /* Code For Divide Goes Here */

  if (divide->expr_1) divide->expr_1->accept(this);
  if (divide->expr_2) divide->expr_2->accept(this);

}

void Skeleton::visitLogicAnd(LogicAnd *logic_and)
{
  /* Code For LogicAnd Goes Here */

  if (logic_and->expr_1) logic_and->expr_1->accept(this);
  if (logic_and->expr_2) logic_and->expr_2->accept(this);

}

void Skeleton::visitRef(Ref *ref)
{
  /* Code For Ref Goes Here */

  if (ref->expr_) ref->expr_->accept(this);

}

void Skeleton::visitDeref(Deref *deref)
{
  /* Code For Deref Goes Here */

  if (deref->expr_) deref->expr_->accept(this);

}

void Skeleton::visitApplication(Application *application)
{
  /* Code For Application Goes Here */

  if (application->expr_) application->expr_->accept(this);
  if (application->listexpr_) application->listexpr_->accept(this);

}

void Skeleton::visitDotRecord(DotRecord *dot_record)
{
  /* Code For DotRecord Goes Here */

  if (dot_record->expr_) dot_record->expr_->accept(this);
  visitSaulIdent(dot_record->saulident_);

}

void Skeleton::visitDotTuple(DotTuple *dot_tuple)
{
  /* Code For DotTuple Goes Here */

  if (dot_tuple->expr_) dot_tuple->expr_->accept(this);
  visitInteger(dot_tuple->integer_);

}

void Skeleton::visitTuple(Tuple *tuple)
{
  /* Code For Tuple Goes Here */

  if (tuple->listexpr_) tuple->listexpr_->accept(this);

}

void Skeleton::visitRecord(Record *record)
{
  /* Code For Record Goes Here */

  if (record->listbinding_) record->listbinding_->accept(this);

}

void Skeleton::visitPanic(Panic *panic)
{
  /* Code For Panic Goes Here */


}

void Skeleton::visitInl(Inl *inl)
{
  /* Code For Inl Goes Here */

  if (inl->expr_) inl->expr_->accept(this);

}

void Skeleton::visitInr(Inr *inr)
{
  /* Code For Inr Goes Here */

  if (inr->expr_) inr->expr_->accept(this);

}

void Skeleton::visitSucc(Succ *succ)
{
  /* Code For Succ Goes Here */

  if (succ->expr_) succ->expr_->accept(this);

}

void Skeleton::visitLogicNot(LogicNot *logic_not)
{
  /* Code For LogicNot Goes Here */

  if (logic_not->expr_) logic_not->expr_->accept(this);

}

void Skeleton::visitPred(Pred *pred)
{
  /* Code For Pred Goes Here */

  if (pred->expr_) pred->expr_->accept(this);

}

void Skeleton::visitIsZero(IsZero *is_zero)
{
  /* Code For IsZero Goes Here */

  if (is_zero->expr_) is_zero->expr_->accept(this);

}

void Skeleton::visitNatRec(NatRec *nat_rec)
{
  /* Code For NatRec Goes Here */

  if (nat_rec->expr_1) nat_rec->expr_1->accept(this);
  if (nat_rec->expr_2) nat_rec->expr_2->accept(this);
  if (nat_rec->expr_3) nat_rec->expr_3->accept(this);

}

void Skeleton::visitConstTrue(ConstTrue *const_true)
{
  /* Code For ConstTrue Goes Here */


}

void Skeleton::visitConstFalse(ConstFalse *const_false)
{
  /* Code For ConstFalse Goes Here */


}

void Skeleton::visitConstUnit(ConstUnit *const_unit)
{
  /* Code For ConstUnit Goes Here */


}

void Skeleton::visitConstInt(ConstInt *const_int)
{
  /* Code For ConstInt Goes Here */

  visitInteger(const_int->integer_);

}

void Skeleton::visitVar(Var *var)
{
  /* Code For Var Goes Here */

  visitSaulIdent(var->saulident_);

}

void Skeleton::visitARecordFieldType(ARecordFieldType *a_record_field_type)
{
  /* Code For ARecordFieldType Goes Here */

  visitSaulIdent(a_record_field_type->saulident_);
  if (a_record_field_type->type_) a_record_field_type->type_->accept(this);

}


void Skeleton::visitListSaulIdent(ListSaulIdent *list_saul_ident)
{
  for (ListSaulIdent::iterator i = list_saul_ident->begin() ; i != list_saul_ident->end() ; ++i)
  {
    visitSaulIdent(*i) ;
  }
}

void Skeleton::visitListDecl(ListDecl *list_decl)
{
  for (ListDecl::iterator i = list_decl->begin() ; i != list_decl->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListLocalDecl(ListLocalDecl *list_local_decl)
{
  for (ListLocalDecl::iterator i = list_local_decl->begin() ; i != list_local_decl->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListAnnotation(ListAnnotation *list_annotation)
{
  for (ListAnnotation::iterator i = list_annotation->begin() ; i != list_annotation->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListParamDecl(ListParamDecl *list_param_decl)
{
  for (ListParamDecl::iterator i = list_param_decl->begin() ; i != list_param_decl->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListType(ListType *list_type)
{
  for (ListType::iterator i = list_type->begin() ; i != list_type->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListMatchCase(ListMatchCase *list_match_case)
{
  for (ListMatchCase::iterator i = list_match_case->begin() ; i != list_match_case->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListPattern(ListPattern *list_pattern)
{
  for (ListPattern::iterator i = list_pattern->begin() ; i != list_pattern->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListLabelledPattern(ListLabelledPattern *list_labelled_pattern)
{
  for (ListLabelledPattern::iterator i = list_labelled_pattern->begin() ; i != list_labelled_pattern->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListBinding(ListBinding *list_binding)
{
  for (ListBinding::iterator i = list_binding->begin() ; i != list_binding->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListExpr(ListExpr *list_expr)
{
  for (ListExpr::iterator i = list_expr->begin() ; i != list_expr->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListRecordFieldType(ListRecordFieldType *list_record_field_type)
{
  for (ListRecordFieldType::iterator i = list_record_field_type->begin() ; i != list_record_field_type->end() ; ++i)
  {
    (*i)->accept(this);
  }
}


void Skeleton::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void Skeleton::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void Skeleton::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void Skeleton::visitString(String x)
{
  /* Code for String Goes Here */
}

void Skeleton::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}

void Skeleton::visitSaulIdent(SaulIdent x)
{
  /* Code for SaulIdent Goes Here */
}


}
